# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    # Copyright (c) 2015 Microsoft Corporation
    - 'include/dsn/service_api_cpp.h'
    - 'include/dsn/toollet/fault_injector.h'
    - 'include/dsn/toollet/tracer.h'
    - 'include/dsn/toollet/profiler.h'
    - 'include/dsn/tool-api/task.h'
    - 'include/dsn/tool-api/file_io.h'
    - 'include/dsn/tool-api/task_code.h'
    - 'include/dsn/tool-api/task_queue.h'
    - 'include/dsn/tool-api/command_manager.h'
    - 'include/dsn/tool-api/env_provider.h'
    - 'include/dsn/tool-api/future_types.h'
    - 'include/dsn/tool-api/global_config.h'
    - 'include/dsn/tool-api/group_address.h'
    - 'include/dsn/tool-api/aio_task.h'
    - 'include/dsn/tool-api/gpid.h'
    - 'include/dsn/tool-api/rpc_address.h'
    - 'include/dsn/tool-api/zlocks.h'
    - 'include/dsn/tool-api/network.h'
    - 'include/dsn/tool-api/timer_service.h'
    - 'include/dsn/tool-api/task_tracker.h'
    - 'include/dsn/tool-api/uniq_timestamp_us.h'
    - 'include/dsn/tool-api/task_worker.h'
    - 'include/dsn/tool-api/thread_access_checker.h'
    - 'include/dsn/tool-api/threadpool_spec.h'
    - 'include/dsn/tool-api/rpc_message.h'
    - 'include/dsn/tool-api/async_calls.h'
    - 'include/dsn/tool-api/logging_provider.h'
    - 'include/dsn/tool-api/message_parser.h'
    - 'include/dsn/tool-api/auto_codes.h'
    - 'include/dsn/tool-api/task_spec.h'
    - 'include/dsn/dist/nfs_node.h'
    - 'include/dsn/dist/distributed_lock_service.h'
    - 'include/dsn/dist/failure_detector.h'
    - 'include/dsn/dist/meta_state_service.h'
    - 'include/dsn/dist/failure_detector_multimaster.h'
    - 'include/dsn/dist/replication.h'
    - 'include/dsn/dist/replication/replication.codes.h'
    - 'include/dsn/dist/replication/mutation_log_tool.h'
    - 'include/dsn/dist/replication/meta_service_app.h'
    - 'include/dsn/dist/replication/replica_test_utils.h'
    - 'include/dsn/dist/replication/replication_other_types.h'
    - 'include/dsn/dist/replication/replica_envs.h'
    - 'include/dsn/dist/replication/replication_service_app.h'
    - 'include/dsn/dist/replication/replication_app_base.h'
    - 'include/dsn/dist/replication/partition_resolver.h'
    - 'include/dsn/dist/replication/replication_ddl_client.h'
    - 'include/dsn/dist/replication/replica_base.h'
    - 'include/dsn/dist/failure_detector/fd.client.h'
    - 'include/dsn/dist/failure_detector/fd.server.h'
    - 'include/dsn/dist/failure_detector/failure_detector.h'
    - 'include/dsn/dist/failure_detector/fd.code.definition.h'
    - 'include/dsn/utils/time_utils.h'
    - 'include/dsn/cpp/rpc_stream.h'
    - 'include/dsn/cpp/serialization.h'
    - 'include/dsn/cpp/service_app.h'
    - 'include/dsn/cpp/json_helper.h'
    - 'include/dsn/cpp/serialization_helper/thrift_helper.h'
    - 'include/dsn/cpp/serverlet.h'
    - 'include/dsn/tool_api.h'
    - 'include/dsn/service_api_c.h'
    - 'include/dsn/c/api_layer1.h'
    - 'include/dsn/c/api_utilities.h'
    - 'include/dsn/c/api_task.h'
    - 'include/dsn/c/api_common.h'
    - 'include/dsn/c/app_model.h'
    - 'include/dsn/perf_counter/perf_counter_wrapper.h'
    - 'include/dsn/perf_counter/perf_counters.h'
    - 'include/dsn/perf_counter/perf_counter.h'
    - 'include/dsn/tool/nativerun.h'
    - 'include/dsn/tool/simulator.h'
    - 'include/dsn/tool/providers.common.h'
    - 'include/dsn/tool/node_scoper.h'
    - 'include/dsn/utility/filesystem.h'
    - 'include/dsn/utility/function_traits.h'
    - 'include/dsn/utility/utils.h'
    - 'include/dsn/utility/work_queue.h'
    - 'include/dsn/utility/customizable_id.h'
    - 'include/dsn/utility/synchronize.h'
    - 'include/dsn/utility/join_point.h'
    - 'include/dsn/utility/factory_store.h'
    - 'include/dsn/utility/blob.h'
    - 'include/dsn/utility/ports.h'
    - 'include/dsn/utility/fixed_size_buffer_pool.h'
    - 'include/dsn/utility/autoref_ptr.h'
    - 'include/dsn/utility/errors.h'
    - 'include/dsn/utility/config_helper.h'
    - 'include/dsn/utility/configuration.h'
    - 'include/dsn/utility/priority_queue.h'
    - 'include/dsn/utility/optional.h'
    - 'include/dsn/utility/exp_delay.h'
    - 'include/dsn/utility/chrono_literals.h'
    - 'include/dsn/utility/extensible_object.h'
    - 'include/dsn/utility/singleton_store.h'
    - 'include/dsn/utility/enum_helper.h'
    - 'include/dsn/utility/apply.h'
    - 'include/dsn/utility/link.h'
    - 'include/dsn/utility/dlib.h'
    - 'include/dsn/utility/config_api.h'
    - 'src/tools/mutation_log_tool.cpp'
    - 'src/nfs/nfs_code_definition.h'
    - 'src/nfs/nfs_client_impl.cpp'
    - 'src/nfs/nfs_server_impl.h'
    - 'src/nfs/nfs_node_impl.cpp'
    - 'src/nfs/nfs_node_simple.h'
    - 'src/nfs/nfs_server_impl.cpp'
    - 'src/nfs/nfs_client_impl.h'
    - 'src/runtime/tool_api.cpp'
    - 'src/runtime/core_main.cpp'
    - 'src/runtime/message_utils.cpp'
    - 'src/runtime/fault_injector.cpp'
    - 'src/runtime/env.sim.cpp'
    - 'src/runtime/simulator.cpp'
    - 'src/runtime/threadpool_code.cpp'
    - 'src/runtime/profiler.cpp'
    - 'src/runtime/test/rpc.cpp'
    - 'src/runtime/test/pipeline_test.cpp'
    - 'src/runtime/test/message_utils_test.cpp'
    - 'src/runtime/test/test_utils.h'
    - 'src/runtime/test/corrupt_message.cpp'
    - 'src/runtime/test/service_api_c.cpp'
    - 'src/runtime/test/lpc.cpp'
    - 'src/runtime/test/rpc_message.cpp'
    - 'src/runtime/test/task_engine.cpp'
    - 'src/runtime/test/sim_lock.cpp'
    - 'src/runtime/test/async_call.cpp'
    - 'src/runtime/test/rpc_holder_test.cpp'
    - 'src/runtime/test/netprovider.cpp'
    - 'src/runtime/test/main.cpp'
    - 'src/runtime/scheduler.h'
    - 'src/runtime/env.sim.h'
    - 'src/runtime/service_api_c.cpp'
    - 'src/runtime/service_engine.cpp'
    - 'src/runtime/scheduler.cpp'
    - 'src/runtime/zlocks.cpp'
    - 'src/runtime/service_engine.h'
    - 'src/runtime/providers.common.cpp'
    - 'src/runtime/task/task_worker.cpp'
    - 'src/runtime/task/task_engine.h'
    - 'src/runtime/task/simple_task_queue.cpp'
    - 'src/runtime/task/simple_task_queue.h'
    - 'src/runtime/task/hpc_task_queue.h'
    - 'src/runtime/task/task_tracker.cpp'
    - 'src/runtime/task/hpc_task_queue.cpp'
    - 'src/runtime/task/task_engine.cpp'
    - 'src/runtime/task/task.cpp'
    - 'src/runtime/task/task_spec.cpp'
    - 'src/runtime/task/task_engine.sim.cpp'
    - 'src/runtime/task/task_queue.cpp'
    - 'src/runtime/task/task_code.cpp'
    - 'src/runtime/task/task_engine.sim.h'
    - 'src/runtime/profiler_header.h'
    - 'src/runtime/tracer.cpp'
    - 'src/runtime/nativerun.cpp'
    - 'src/runtime/rpc/network.cpp'
    - 'src/runtime/rpc/raw_message_parser.cpp'
    - 'src/runtime/rpc/raw_message_parser.h'
    - 'src/runtime/rpc/asio_net_provider.h'
    - 'src/runtime/rpc/asio_rpc_session.cpp'
    - 'src/runtime/rpc/asio_net_provider.cpp'
    - 'src/runtime/rpc/network.sim.h'
    - 'src/runtime/rpc/thrift_message_parser.cpp'
    - 'src/runtime/rpc/rpc_engine.h'
    - 'src/runtime/rpc/network.sim.cpp'
    - 'src/runtime/rpc/rpc_message.cpp'
    - 'src/runtime/rpc/dsn_message_parser.cpp'
    - 'src/runtime/rpc/dsn_message_parser.h'
    - 'src/runtime/rpc/thrift_message_parser.h'
    - 'src/runtime/rpc/message_parser.cpp'
    - 'src/runtime/rpc/rpc_task.cpp'
    - 'src/runtime/rpc/asio_rpc_session.h'
    - 'src/runtime/rpc/message_parser_manager.h'
    - 'src/runtime/rpc/rpc_engine.cpp'
    - 'src/runtime/global_config.cpp'
    - 'src/meta/meta_state_service_zookeeper.h'
    - 'src/meta/server_state.cpp'
    - 'src/meta/greedy_load_balancer.cpp'
    - 'src/meta/dump_file.h'
    - 'src/meta/meta_service.cpp'
    - 'src/meta/test/misc/misc.h'
    - 'src/meta/test/meta_state/main.cpp'
    - 'src/meta/test/meta_split_service_test.cpp'
    - 'src/meta/test/duplication_info_test.cpp'
    - 'src/meta/test/meta_state_service_utils_test.cpp'
    - 'src/meta/test/meta_service_test_app.h'
    - 'src/meta/test/meta_app_envs_test.cpp'
    - 'src/meta/test/meta_duplication_service_test.cpp'
    - 'src/meta/meta_state_service_zookeeper.cpp'
    - 'src/meta/distributed_lock_service_simple.cpp'
    - 'src/meta/meta_server_failure_detector.cpp'
    - 'src/meta/meta_data.h'
    - 'src/meta/meta_state_service_simple.h'
    - 'src/meta/meta_server_failure_detector.h'
    - 'src/meta/server_state.h'
    - 'src/meta/distributed_lock_service_simple.h'
    - 'src/meta/greedy_load_balancer.h'
    - 'src/meta/server_load_balancer.h'
    - 'src/meta/meta_state_service_simple.cpp'
    - 'src/meta/meta_options.h'
    - 'src/meta/meta_options.cpp'
    - 'src/meta/meta_service.h'
    - 'src/meta/meta_data.cpp'
    - 'src/meta/meta_service_app.cpp'
    - 'src/aio/aio_provider.h'
    - 'src/aio/test/aio.cpp'
    - 'src/aio/disk_engine.h'
    - 'src/aio/file_io.cpp'
    - 'src/aio/aio_provider.cpp'
    - 'src/aio/native_linux_aio_provider.h'
    - 'src/aio/native_linux_aio_provider.cpp'
    - 'src/aio/disk_engine.cpp'
    - 'src/utils/thread_access_checker.cpp'
    - 'src/utils/utils.cpp'
    - 'src/utils/shared_io_service.h'
    - 'src/utils/logging.cpp'
    - 'src/utils/test/lock.std.cpp'
    - 'src/utils/test/utils.cpp'
    - 'src/utils/test/json_helper_test.cpp'
    - 'src/utils/test/logging.cpp'
    - 'src/utils/test/output_utils_test.cpp'
    - 'src/utils/test/time_utils_test.cpp'
    - 'src/utils/test/env.cpp'
    - 'src/utils/test/join_point_test.cpp'
    - 'src/utils/test/address.cpp'
    - 'src/utils/test/configuration.cpp'
    - 'src/utils/test/priority_queue.cpp'
    - 'src/utils/test/logger.cpp'
    - 'src/utils/test/file_utils.cpp'
    - 'src/utils/test/command_manager.cpp'
    - 'src/utils/test/fmt_logging_test.cpp'
    - 'src/utils/test/string_conv_test.cpp'
    - 'src/utils/test/sema.cpp'
    - 'src/utils/simple_logger.cpp'
    - 'src/utils/strings.cpp'
    - 'src/utils/error_code.cpp'
    - 'src/utils/simple_logger.h'
    - 'src/utils/config_api.cpp'
    - 'src/utils/filesystem.cpp'
    - 'src/utils/coredump.posix.cpp'
    - 'src/utils/configuration.cpp'
    - 'src/utils/gpid.cpp'
    - 'src/utils/rpc_address.cpp'
    - 'src/utils/command_manager.cpp'
    - 'src/utils/coredump.h'
    - 'src/utils/lockp.std.h'
    - 'src/utils/zlock_provider.h'
    - 'src/zookeeper/lock_types.h'
    - 'src/zookeeper/zookeeper_error.h'
    - 'src/zookeeper/test/distributed_lock_zookeeper.cpp'
    - 'src/zookeeper/test/main.cpp'
    - 'src/zookeeper/zookeeper_error.cpp'
    - 'src/zookeeper/zookeeper_session.cpp'
    - 'src/zookeeper/zookeeper_session_mgr.h'
    - 'src/zookeeper/lock_struct.h'
    - 'src/zookeeper/distributed_lock_service_zookeeper.cpp'
    - 'src/zookeeper/distributed_lock_service_zookeeper.h'
    - 'src/zookeeper/zookeeper_session.h'
    - 'src/zookeeper/lock_struct.cpp'
    - 'src/zookeeper/zookeeper_session_mgr.cpp'
    - 'src/common/consensus.thrift'
    - 'src/common/replication_common.cpp'
    - 'src/common/test/duplication_common_test.cpp'
    - 'src/common/test/main.cpp'
    - 'src/common/fs_manager.cpp'
    - 'src/common/metadata.thrift'
    - 'src/common/meta_admin.thrift'
    - 'src/common/replication_common.h'
    - 'src/common/replica_admin.thrift'
    - 'src/http/http_message_parser.cpp'
    - 'src/http/http_message_parser.h'
    - 'src/replica/replica_context.h'
    - 'src/replica/log_file_stream.h'
    - 'src/replica/mutation_log.h'
    - 'src/replica/replica_test_utils.cpp'
    - 'src/replica/mutation_cache.cpp'
    - 'src/replica/mutation_log_utils.h'
    - 'src/replica/replica_config.cpp'
    - 'src/replica/test/replica_test_base.h'
    - 'src/replica/test/mutation_log_learn_test.cpp'
    - 'src/replica/test/mock_utils.h'
    - 'src/replica/test/mutation_log_test.cpp'
    - 'src/replica/mutation_log_utils.cpp'
    - 'src/replica/replica_learn.cpp'
    - 'src/replica/mutation_log.cpp'
    - 'src/replica/replica_2pc.cpp'
    - 'src/replica/log_file.cpp'
    - 'src/replica/replication_app_base.cpp'
    - 'src/replica/mutation_cache.h'
    - 'src/replica/replica_failover.cpp'
    - 'src/replica/replica_init.cpp'
    - 'src/replica/storage/simple_kv/simple_kv.server.impl.h'
    - 'src/replica/storage/simple_kv/simple_kv.code.definition.h'
    - 'src/replica/storage/simple_kv/test/common.cpp'
    - 'src/replica/storage/simple_kv/test/simple_kv.server.impl.h'
    - 'src/replica/storage/simple_kv/test/client.h'
    - 'src/replica/storage/simple_kv/test/injector.cpp'
    - 'src/replica/storage/simple_kv/test/client.cpp'
    - 'src/replica/storage/simple_kv/test/checker.h'
    - 'src/replica/storage/simple_kv/test/simple_kv.server.impl.cpp'
    - 'src/replica/storage/simple_kv/test/common.h'
    - 'src/replica/storage/simple_kv/test/checker.cpp'
    - 'src/replica/storage/simple_kv/test/case.h'
    - 'src/replica/storage/simple_kv/test/simple_kv.main.cpp'
    - 'src/replica/storage/simple_kv/test/injector.h'
    - 'src/replica/storage/simple_kv/test/case.cpp'
    - 'src/replica/storage/simple_kv/simple_kv.app.example.h'
    - 'src/replica/storage/simple_kv/simple_kv.server.impl.cpp'
    - 'src/replica/storage/simple_kv/simple_kv.main.cpp'
    - 'src/replica/storage/simple_kv/simple_kv.server.h'
    - 'src/replica/replica_check.cpp'
    - 'src/replica/replication_service_app.cpp'
    - 'src/replica/log_file.h'
    - 'src/replica/replica_stub.cpp'
    - 'src/replica/prepare_list.h'
    - 'src/replica/replica.cpp'
    - 'src/replica/mutation.cpp'
    - 'src/replica/replica_context.cpp'
    - 'src/replica/mutation.h'
    - 'src/replica/replica.h'
    - 'src/replica/prepare_list.cpp'
    - 'src/replica/replica_stub.h'
    - 'src/replica/replica_chkpt.cpp'
    - 'src/failure_detector/test/main.cpp'
    - 'src/failure_detector/failure_detector_multimaster.cpp'
    - 'src/failure_detector/failure_detector.cpp'
    - 'src/client/partition_resolver_manager.cpp'
    - 'src/client/replication_ddl_client.cpp'
    - 'src/client/partition_resolver_simple.cpp'
    - 'src/client/partition_resolver.cpp'
    - 'src/client/partition_resolver_manager.h'
    - 'src/client/partition_resolver_simple.h'
    - 'src/perf_counter/perf_counters.cpp'
    - 'src/perf_counter/test/perf_counters_test.cpp'
    - 'src/perf_counter/test/perf_counter_test.cpp'
    # Copyright (c) Facebook, Inc
    - 'include/dsn/utility/TokenBucket.h'
    - 'src/utils/test/TokenBucketTest.cpp'
    - 'src/utils/test/TokenBucketTest.h'
    # https://github.com/preshing/cpp11-on-multicore/blob/master/LICENSE
    - 'include/dsn/utility/hpc_locks/autoreseteventcondvar.h'
    - 'include/dsn/utility/hpc_locks/rwlock.h'
    - 'include/dsn/utility/hpc_locks/autoresetevent.h'
    - 'include/dsn/utility/hpc_locks/sema.h'
    - 'include/dsn/utility/hpc_locks/bitfield.h'
    - 'include/dsn/utility/hpc_locks/benaphore.h'
    # Copyright (c) xxxx The Chromium Authors
    - 'src/runtime/build_config.h'
    - 'src/utils/test/autoref_ptr_test.cpp'
    - 'include/dsn/utility/safe_strerror_posix.h'
    - '.licenserc.yaml'
    - 'src/runtime/build_config.h'
    - 'src/utils/test/autoref_ptr_test.cpp'
    - 'src/utils/safe_strerror_posix.cpp'
    # Copyright 2017 The Abseil Authors
    - 'include/dsn/utility/absl/base/internal/invoke.h'
    - 'include/dsn/utility/absl/utility/utility.h'
    - 'include/dsn/utility/smart_pointers.h'
    - 'include/dsn/utility/string_view.h'
    - 'src/utils/test/memutil_test.cpp'
    - 'src/utils/test/string_view_test.cpp'
    - 'src/utils/test/smart_pointers_test.cpp'
    - 'src/utils/memutil.h'
    - 'src/utils/string_view.cpp'
    # Copyright (c) 2010-2011, Rob Jansen
    - 'bin/FindRT.cmake'
    - 'bin/FindDL.cmake'
    # Copyright (c) 2017 Guillaume Papin
    - 'scripts/linux/run-clang-format.py'

  comment: on-failure
