# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
header:
  license:
    spdx-id: MIT
    copyright-owner: Microsoft Corporation
    content: |
      The MIT License (MIT)
     
      Copyright (c) 2015 Microsoft Corporation
     
      -=- Robust Distributed System Nucleus (rDSN) -=-
     
      Permission is hereby granted, free of charge, to any person obtaining a copy
      of this software and associated documentation files (the "Software"), to deal
      in the Software without restriction, including without limitation the rights
      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
      copies of the Software, and to permit persons to whom the Software is
      furnished to do so, subject to the following conditions:
     
      The above copyright notice and this permission notice shall be included in
      all copies or substantial portions of the Software.
     
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
      THE SOFTWARE.

  paths-ignore:
    # All the type of licenses of this project should be added to LICENSE.
    - 'LICENSE'
    # Apache license 2.0
    - 'src/common/backup.thrift'
    - 'src/common/bulk_load.thrift'
    - 'src/common/duplication.thrift'
    - 'src/common/partition_split.thrift'
    - 'src/runtime/rpc/request_meta.thrift'
    - 'src/runtime/security/security.thrift'
    - '.licenserc.yaml'
    - 'bin/FindJemalloc.cmake'
    - 'bin/compiler_info.cmake'
    - 'bin/thrift_utils.cmake'
    - 'CONTRIBUTING.md'
    - '.github/workflows/check_license_header.yaml'
    - '.github/workflows/compilation.yaml'
    - '.github/workflows/cpp_actions.yaml'
    - '.github/workflows/cpp_always_pass_actions.yaml'
    - '.github/workflows/issue_ref.yaml'
    - '.github/workflows/non_cpp_actions.yaml'
    - 'include/dsn/dist/fmt_logging.h'
    - 'include/dsn/dist/block_service.h'
    - 'include/dsn/dist/common.h'
    - 'include/dsn/dist/remote_command.h'
    - 'include/dsn/dist/replication/mutation_duplicator.h'
    - 'include/dsn/dist/replication/duplication_common.h'
    - 'include/dsn/dist/replication/replication_types.h'
    - 'include/dsn/utility/clock.h'
    - 'include/dsn/utility/preloadable.h'
    - 'include/dsn/utility/sys_exit_hook.h'
    - 'include/dsn/utils/token_buckets.h'
    - 'include/dsn/utils/latency_tracer.h'
    - 'include/dsn/utils/token_bucket_throttling_controller.h'
    - 'include/dsn/http/http_server.h'
    - 'include/dsn/cpp/message_utils.h'
    - 'include/dsn/cpp/rpc_holder.h'
    - 'include/dsn/cpp/pipeline.h'
    - 'include/dsn/perf_counter/perf_counter_utils.h'
    - 'include/dsn/utility/endians.h'
    - 'include/dsn/utility/fail_point.h'
    - 'include/dsn/utility/singleton.h'
    - 'include/dsn/utility/process_utils.h'
    - 'include/dsn/utility/flags.h'
    - 'include/dsn/utility/string_conv.h'
    - 'include/dsn/utility/timer.h'
    - 'include/dsn/utility/output_utils.h'
    - 'include/dsn/utility/string_splitter.h'
    - 'include/dsn/utility/rand.h'
    - 'include/dsn/utility/math.h'
    - 'include/dsn/utility/defer.h'
    - 'include/dsn/utility/alloc.h'
    - 'include/dsn/utility/casts.h'
    - 'include/dsn/utility/long_adder.h'
    - 'include/dsn/utility/metrics.h'
    - 'include/dsn/utility/nth_element.h'
    - 'src/aio/aio_task.cpp'
    - 'src/aio/test/main.cpp'
    - 'src/meta/test/meta_http_service_test.cpp'
    - 'src/meta/test/meta_service_test.cpp'
    - 'src/perf_counter/perf_counter_atomic.h'
    - 'src/perf_counter/test/main.cpp'
    - 'src/remote_cmd/remote_command.cpp'
    - 'src/runtime/sim_clock.h'
    - 'src/runtime/test/replica_access_controller_test.cpp'
    - 'src/runtime/test/server_negotiation_test.cpp'
    - 'src/runtime/test/negotiation_manager_test.cpp'
    - 'src/runtime/test/task_test.cpp'
    - 'src/runtime/test/client_negotiation_test.cpp'
    - 'src/runtime/test/message_reader_test.cpp'
    - 'src/runtime/test/thrift_message_parser_test.cpp'
    - 'src/runtime/test/meta_access_controller_test.cpp'
    - 'src/runtime/security/sasl_wrapper.h'
    - 'src/runtime/security/sasl_server_wrapper.cpp'
    - 'src/runtime/security/server_negotiation.cpp'
    - 'src/runtime/security/server_negotiation.h'
    - 'src/runtime/security/sasl_server_wrapper.h'
    - 'src/runtime/security/access_controller.h'
    - 'src/runtime/security/access_controller.cpp'
    - 'src/runtime/security/sasl_init.h'
    - 'src/runtime/security/negotiation_manager.h'
    - 'src/runtime/security/sasl_client_wrapper.cpp'
    - 'src/runtime/security/kinit_context.cpp'
    - 'src/runtime/security/client_negotiation.cpp'
    - 'src/runtime/security/sasl_init.cpp'
    - 'src/runtime/security/kinit_context.h'
    - 'src/runtime/security/negotiation.cpp'
    - 'src/runtime/security/negotiation_manager.cpp'
    - 'src/runtime/security/client_negotiation.h'
    - 'src/runtime/security/negotiation.h'
    - 'src/runtime/security/security.thrift'
    - 'src/runtime/security/sasl_wrapper.cpp'
    - 'src/runtime/security/replica_access_controller.cpp'
    - 'src/runtime/security/meta_access_controller.h'
    - 'src/runtime/security/init.cpp'
    - 'src/runtime/security/init.h'
    - 'src/runtime/security/replica_access_controller.h'
    - 'src/runtime/security/sasl_client_wrapper.h'
    - 'src/runtime/security/negotiation_utils.h'
    - 'src/runtime/security/meta_access_controller.cpp'
    - 'src/runtime/rpc/request_meta.thrift'
    - 'src/meta/meta_state_service_utils_impl.h'
    - 'src/meta/meta_bulk_load_ingestion_context.cpp'
    - 'src/meta/partition_guardian.h'
    - 'src/meta/app_balance_policy.cpp'
    - 'src/meta/test/meta_test_base.h'
    - 'src/meta/test/meta_app_operation_test.cpp'
    - 'src/meta/test/meta_mauanl_compaction_test.cpp'
    - 'src/meta/test/meta_bulk_load_service_test.cpp'
    - 'src/meta/test/ford_fulkerson_test.cpp'
    - 'src/meta/test/cluster_balance_policy_test.cpp'
    - 'src/meta/test/meta_test_base.cpp'
    - 'src/meta/test/dummy_balancer.h'
    - 'src/meta/test/meta_bulk_load_ingestion_test.cpp'
    - 'src/meta/test/meta_backup_test.cpp'
    - 'src/meta/test/backup_test.cpp'
    - 'src/meta/test/main.cpp'
    - 'src/meta/test/server_state_restore_test.cpp'
    - 'src/meta/test/copy_replica_operation_test.cpp'
    - 'src/meta/app_env_validator.cpp'
    - 'src/meta/meta_rpc_types.h'
    - 'src/meta/load_balance_policy.cpp'
    - 'src/meta/meta_bulk_load_service.cpp'
    - 'src/meta/cluster_balance_policy.cpp'
    - 'src/meta/meta_split_service.cpp'
    - 'src/meta/cluster_balance_policy.h'
    - 'src/meta/app_env_validator.h'
    - 'src/meta/meta_bulk_load_service.h'
    - 'src/meta/backup_engine.cpp'
    - 'src/meta/backup_engine.h'
    - 'src/meta/meta_backup_service.cpp'
    - 'src/meta/meta_backup_service.h'
    - 'src/meta/meta_http_service.h'
    - 'src/meta/meta_split_service.h'
    - 'src/meta/meta_state_service_utils.h'
    - 'src/meta/meta_state_service_utils.cpp'
    - 'src/meta/meta_http_service.cpp'
    - 'src/meta/app_balance_policy.h'
    - 'src/meta/partition_guardian.cpp'
    - 'src/meta/meta_bulk_load_ingestion_context.h'
    - 'src/meta/load_balance_policy.h'
    - 'src/meta/duplication/duplication_info.h'
    - 'src/meta/duplication/meta_duplication_service.h'
    - 'src/meta/duplication/duplication_info.cpp'
    - 'src/meta/duplication/meta_duplication_service.cpp'
    - 'src/meta/server_state_restore.cpp'
    - 'src/utils/clock.cpp'
    - 'src/utils/flags.cpp'
    - 'src/utils/throttling_controller.h'
    - 'src/utils/time_utils.cpp'
    - 'src/utils/test/rand_test.cpp'
    - 'src/utils/test/latency_tracer_test.cpp'
    - 'src/utils/test/binary_reader_test.cpp'
    - 'src/utils/test/fail_point_test.cpp'
    - 'src/utils/test/hostname_test.cpp'
    - 'src/utils/test/token_bucket_throttling_controller_test.cpp'
    - 'src/utils/test/file_system_test.cpp'
    - 'src/utils/test/endian_test.cpp'
    - 'src/utils/test/token_buckets_test.cpp'
    - 'src/utils/test/flag_test.cpp'
    - 'src/utils/test/main.cpp'
    - 'src/utils/fail_point.cpp'
    - 'src/utils/math.cpp'
    - 'src/utils/latency_tracer.cpp'
    - 'src/utils/fail_point_impl.h'
    - 'src/utils/process_utils.cpp'
    - 'src/utils/token_bucket_throttling_controller.cpp'
    - 'src/utils/token_buckets.cpp'
    - 'src/utils/rand.cpp'
    - 'src/utils/throttling_controller.cpp'
    - 'src/utils/output_utils.cpp'
    - 'src/utils/alloc.cpp'
    - 'src/utils/long_adder.cpp'
    - 'src/utils/long_adder_bench/long_adder_bench.cpp'
    - 'src/utils/metrics.cpp'
    - 'src/utils/shared_io_service.cpp'
    - 'src/utils/test/long_adder_test.cpp'
    - 'src/utils/test/metrics_test.cpp'
    - 'src/utils/test/nth_element_bench/nth_element_bench.cpp'
    - 'src/utils/test/nth_element_test.cpp'
    - 'src/utils/test/nth_element_utils.h'
    - 'src/utils/test/percentile_utils.h'
    - 'src/common/partition_split.thrift'
    - 'src/common/common.cpp'
    - 'src/common/consensus.thrift'
    - 'src/common/backup_common.h'
    - 'src/common/bulk_load_common.cpp'
    - 'src/common/test/fs_manager_test.cpp'
    - 'src/common/test/common_test.cpp'
    - 'src/common/test/replication_common_test.cpp'
    - 'src/common/fs_manager.h'
    - 'src/common/backup_common.cpp'
    - 'src/common/bulk_load_common.h'
    - 'src/common/duplication.thrift'
    - 'src/common/manual_compact.h'
    - 'src/common/duplication_common.cpp'
    - 'src/common/partition_split_common.h'
    - 'src/common/metadata.thrift'
    - 'src/common/meta_admin.thrift'
    - 'src/common/bulk_load.thrift'
    - 'src/common/backup.thrift'
    - 'src/common/replica_admin.thrift'
    - 'src/http/CMakeLists.txt'
    - 'src/http/builtin_http_calls.h'
    - 'src/http/test/http_server_test.cpp'
    - 'src/http/test/perf_counter_http_service_test.cpp'
    - 'src/http/test/uri_decoder_test.cpp'
    - 'src/http/http_server_impl.h'
    - 'src/http/uri_decoder.cpp'
    - 'src/http/uri_decoder.h'
    - 'src/http/http_server.cpp'
    - 'src/http/perf_counter_http_service.cpp'
    - 'src/http/pprof_http_service.cpp'
    - 'src/http/builtin_http_calls.cpp'
    - 'src/http/service_version.cpp'
    - 'src/http/pprof_http_service.h'
    - 'src/http/service_version.h'
    - 'src/http/config_http_service.cpp'
    - 'src/http/http_call_registry.h'
    - 'src/block_service/CMakeLists.txt'
    - 'src/block_service/test/fds_service_test.cpp'
    - 'src/block_service/test/CMakeLists.txt'
    - 'src/block_service/test/hdfs_service_test.cpp'
    - 'src/block_service/test/local_service_test.cpp'
    - 'src/block_service/test/run.sh'
    - 'src/block_service/test/block_service_mock.h'
    - 'src/block_service/test/clear.sh'
    - 'src/block_service/test/main.cpp'
    - 'src/block_service/test/block_service_manager_test.cpp'
    - 'src/block_service/directio_writable_file.h'
    - 'src/block_service/fds/fds_service.cpp'
    - 'src/block_service/fds/fds_service.h'
    - 'src/block_service/block_service_manager.cpp'
    - 'src/block_service/block_service_manager.h'
    - 'src/block_service/local/local_service.cpp'
    - 'src/block_service/local/local_service.h'
    - 'src/block_service/hdfs/hdfs_service.cpp'
    - 'src/block_service/hdfs/hdfs_service.h'
    - 'src/block_service/directio_writable_file.cpp'
    - 'src/replica/replica_disk_migrator.cpp'
    - 'src/replica/split/replica_split_manager.cpp'
    - 'src/replica/split/test/replica_split_test.cpp'
    - 'src/replica/split/test/main.cpp'
    - 'src/replica/split/replica_split_manager.h'
    - 'src/replica/replica_http_service.cpp'
    - 'src/replica/log_block.cpp'
    - 'src/replica/test/replica_learn_test.cpp'
    - 'src/replica/test/log_file_test.cpp'
    - 'src/replica/test/throttling_controller_test.cpp'
    - 'src/replica/test/replica_disk_test_base.h'
    - 'src/replica/test/cold_backup_context_test.cpp'
    - 'src/replica/test/replica_disk_test.cpp'
    - 'src/replica/test/log_block_test.cpp'
    - 'src/replica/test/clear.sh'
    - 'src/replica/test/replica_test.cpp'
    - 'src/replica/test/replica_disk_migrate_test.cpp'
    - 'src/replica/test/main.cpp'
    - 'src/replica/test/backup_block_service_mock.h'
    - 'src/replica/test/open_replica_test.cpp'
    - 'src/replica/replica_backup.cpp'
    - 'src/replica/disk_cleaner.h'
    - 'src/replica/mutation_log_replay.cpp'
    - 'src/replica/bulk_load/test/replica_bulk_loader_test.cpp'
    - 'src/replica/bulk_load/test/main.cpp'
    - 'src/replica/bulk_load/replica_bulk_loader.cpp'
    - 'src/replica/bulk_load/replica_bulk_loader.h'
    - 'src/replica/disk_cleaner.cpp'
    - 'src/replica/replica_disk_migrator.h'
    - 'src/replica/log_block.h'
    - 'src/replica/replica_throttle.cpp'
    - 'src/replica/backup/cold_backup_context.h'
    - 'src/replica/backup/cold_backup_context.cpp'
    - 'src/replica/backup/test/replica_backup_manager_test.cpp'
    - 'src/replica/backup/test/main.cpp'
    - 'src/replica/backup/replica_backup_manager.h'
    - 'src/replica/backup/replica_backup_server.cpp'
    - 'src/replica/backup/replica_backup_manager.cpp'
    - 'src/replica/backup/replica_backup_server.h'
    - 'src/replica/replica_http_service.h'
    - 'src/replica/replica_restore.cpp'
    - 'src/replica/duplication/mutation_batch.h'
    - 'src/replica/duplication/replica_follower.cpp'
    - 'src/replica/duplication/replica_duplicator_manager.cpp'
    - 'src/replica/duplication/duplication_pipeline.cpp'
    - 'src/replica/duplication/replica_follower.h'
    - 'src/replica/duplication/replica_duplicator_manager.h'
    - 'src/replica/duplication/test/replica_http_service_test.cpp'
    - 'src/replica/duplication/test/replica_duplicator_manager_test.cpp'
    - 'src/replica/duplication/test/duplication_sync_timer_test.cpp'
    - 'src/replica/duplication/test/load_from_private_log_test.cpp'
    - 'src/replica/duplication/test/duplication_test_base.h'
    - 'src/replica/duplication/test/replica_follower_test.cpp'
    - 'src/replica/duplication/test/ship_mutation_test.cpp'
    - 'src/replica/duplication/test/mutation_batch_test.cpp'
    - 'src/replica/duplication/test/replica_duplicator_test.cpp'
    - 'src/replica/duplication/test/main.cpp'
    - 'src/replica/duplication/replica_duplicator.h'
    - 'src/replica/duplication/duplication_pipeline.h'
    - 'src/replica/duplication/load_from_private_log.h'
    - 'src/replica/duplication/mutation_batch.cpp'
    - 'src/replica/duplication/duplication_sync_timer.h'
    - 'src/replica/duplication/duplication_sync_timer.cpp'
    - 'src/replica/duplication/load_from_private_log.cpp'
    - 'src/replica/duplication/replica_duplicator.cpp'
    - 'src/perf_counter/builtin_counters.cpp'
    - 'src/perf_counter/builtin_counters.h'
    # Copyright (c) Facebook, Inc
    - 'include/dsn/utility/TokenBucket.h'
    - 'src/utils/test/TokenBucketTest.cpp'
    - 'src/utils/test/TokenBucketTest.h'
    # https://github.com/preshing/cpp11-on-multicore/blob/master/LICENSE
    - 'include/dsn/utility/hpc_locks/autoreseteventcondvar.h'
    - 'include/dsn/utility/hpc_locks/rwlock.h'
    - 'include/dsn/utility/hpc_locks/autoresetevent.h'
    - 'include/dsn/utility/hpc_locks/sema.h'
    - 'include/dsn/utility/hpc_locks/bitfield.h'
    - 'include/dsn/utility/hpc_locks/benaphore.h'
    # Copyright (c) xxxx The Chromium Authors
    - 'src/runtime/build_config.h'
    - 'src/utils/test/autoref_ptr_test.cpp'
    - 'include/dsn/utility/safe_strerror_posix.h'
    - 'src/runtime/build_config.h'
    - 'src/utils/test/autoref_ptr_test.cpp'
    - 'src/utils/safe_strerror_posix.cpp'
    # Copyright 2017 The Abseil Authors
    - 'include/dsn/utility/absl/base/internal/invoke.h'
    - 'include/dsn/utility/absl/utility/utility.h'
    - 'include/dsn/utility/smart_pointers.h'
    - 'include/dsn/utility/string_view.h'
    - 'src/utils/test/memutil_test.cpp'
    - 'src/utils/test/string_view_test.cpp'
    - 'src/utils/test/smart_pointers_test.cpp'
    - 'src/utils/memutil.h'
    - 'src/utils/string_view.cpp'
    # Copyright (c) 2010-2011, Rob Jansen
    - 'bin/FindRT.cmake'
    - 'bin/FindDL.cmake'
    # Copyright (c) 2017 Guillaume Papin
    - 'scripts/linux/run-clang-format.py'
    # need manual fix
    - 'src/failure_detector/test/gtest.filter'
    - 'src/meta/test/meta_state/gtest.filter'
    - 'src/meta/test/suite1'
    - 'src/meta/test/suite2'
    - 'src/nfs/test/nfs_test_file1'
    - 'src/nfs/test/nfs_test_file2'
    - 'src/runtime/test/gtest.filter'
    - 'thirdparty/fix_fds_for_macos.patch'
    - 'thirdparty/fix_s2_for_aarch64.patch'
    - 'thirdparty/fix_thrift_for_cpp11.patch'
    # should be empty, or ignore all comment lines
    - 'src/utils/test/config-empty.ini'

  comment: on-failure
