sudo: required
dist: bionic

language: cpp

compiler:
    - gcc

cache:
    - ccache
    - apt

before_install:
    - sudo apt-get -y install libboost-all-dev libaio-dev clang-format-3.9

before_script:
    - cd thirdparty
    - wget https://github.com/XiaoMi/pegasus-common/releases/download/deps/pegasus-thirdparty-prebuild.zip
    - unzip pegasus-thirdparty-prebuild.zip
    - rm -f pegasus-thirdparty-prebuild.zip
    - cd ..
    - ulimit -c unlimited -S

script:
    - export LD_LIBRARY_PATH=`pwd`/thirdparty/output/lib/:$LD_LIBRARY_PATH
    - ./run.sh test --skip_thirdparty --check --disable_gperf

after_script:
    - ./run.sh stop_zk

notifications:
    email: false
