sudo: required
dist: trusty

language: cpp

os: linux

compiler: 
    - gcc

cache:
    - ccache

before_install:
    - wget https://raw.githubusercontent.com/xiaomi/pegasus-common/master/build-depends.tar.gz
    - tar xf build-depends.tar.gz
    - cd packages
    - ls | xargs sudo dpkg -i --force-depends
    - cd ..

install:
    # - ./run.sh format

before_script:
    - cd thirdparty
    - wget https://raw.githubusercontent.com/xiaomi/pegasus-common/master/pegasus-thirdparty-prebuild.tar.gz
    - tar xf pegasus-thirdparty-prebuild.tar.gz
    - rm -rf pegasus-thirdparty-prebuild.tar.gz
    - wget https://raw.githubusercontent.com/xiaomi/pegasus-common/master/zookeeper-3.4.10.tar.gz
    - mkdir src/
    - tar xf zookeeper-3.4.10.tar.gz -C src
    - rm -rf zookeeper-3.4.10.tar.gz
    - cd ..
    - ulimit -c unlimited -S

script:
    - ./run.sh test --skip_thirdparty

after_script:
    - ./run.sh stop_zk

notifications:
    email: false
