sudo: required
dist: bionic

language: cpp

compiler:
    - gcc

cache:
    - ccache
    - apt
    - directories:
          - /home/travis/build/XiaoMi/rdsn/thirdparty/output

addons:
    apt:
        packages:
            - clang-format-3.9

before_install:
    - wget https://github.com/XiaoMi/pegasus-common/releases/download/deps/build-depends.tar.gz
    - tar xfz build-depends.tar.gz
    - rm -f build-depends.tar.gz
    - cd packages
    - ls | xargs sudo dpkg -i --force-depends
    - cd ..

before_script:
    - cd thirdparty
    - wget https://github.com/XiaoMi/pegasus-common/releases/download/deps/pegasus-thirdparty-prebuild.zip
    - unzip pegasus-thirdparty-prebuild.zip
    - rm -f pegasus-thirdparty-prebuild.zip
    - cd ..
    - ulimit -c unlimited -S

script:
    - ./run.sh test --skip_thirdparty --check --disable_gperf

after_script:
    - ./run.sh stop_zk

notifications:
    email: false
