# Developer Notes:
#
# This config is for github actions. Before merging your changes of this file,
# it's recommended to create a PR against the ci-test branch to test if it works
# as expected.

name: Code Lint and Unit Test

on:
  # run on each pull request
  pull_request:
    types: [ synchronize, opened, reopened ]
    paths:
      - .github/workflows/cpp_actions.yaml
      - CMakeLists.txt
      - bin
      - compile_thrift.py
      - include
      - run.sh
      - scripts
      - src
      - thirdparty
    branches:
      - master
      - 'v[0-9]+.*' # release branch
      - ci-test # testing branch for github action
      - '*dev' # developing branch

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: apachepegasus/clang-format-3.9
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: clang-format
        run: ./scripts/linux/run-clang-format.py --clang-format-executable=clang-format-3.9 -r src include

  test:
    name: Test
    needs: lint
    runs-on: self-hosted
    container:
      image: apachepegasus/thirdparties-bin:ubuntu1804
      env:
        CCACHE_DIR: /tmp/ccache/pegasus
        CCACHE_MAXSIZE: 10G
      volumes:
        # Place ccache compilation intermediate results in host memory, that's shared among containers.
        - /tmp/ccache/pegasus:/tmp/ccache/pegasus
      # Read docs at https://docs.docker.com/storage/tmpfs/ for more details of using tmpfs in docker.
      options: --mount type=tmpfs,destination=/tmp/pegasus --cap-add=SYS_PTRACE
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
      - name: Unpack prebuilt third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty') == false
        run: unzip /root/thirdparties-bin.zip -d ./thirdparty
      - name: Rebuild third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty')
        working-directory: thirdparty
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -B build/
          cmake --build build/ -j $(($(nproc)/2+1))
      - name: Compilation
        run: ./run.sh build -c --skip_thirdparty
      - name: Unit Testing
        run: |
          export LD_LIBRARY_PATH=`pwd`/thirdparty/output/lib:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server          
          ulimit -s unlimited
          ./run.sh test --skip_thirdparty

  test-with-sanitizer-address:
    name: Test With Sanitizer Address
    needs: lint
    runs-on: self-hosted
    container:
      image: apachepegasus/thirdparties-bin:ubuntu1804
      env:
        CCACHE_DIR: /tmp/ccache/pegasus
        CCACHE_MAXSIZE: 10G
      volumes:
        # Place ccache compilation intermediate results in host memory, that's shared among containers.
        - /tmp/ccache/pegasus:/tmp/ccache/pegasus
      # Read docs at https://docs.docker.com/storage/tmpfs/ for more details of using tmpfs in docker.
      options: --mount type=tmpfs,destination=/tmp/pegasus --cap-add=SYS_PTRACE
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
      - name: Unpack prebuilt third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty') == false
        run: unzip /root/thirdparties-bin.zip -d ./thirdparty
      - name: Rebuild third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty')
        working-directory: thirdparty
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -B build/
          cmake --build build/ -j $(($(nproc)/2+1))
      - name: Compilation
        run: ./run.sh build -c --sanitizer address --skip_thirdparty --disable_gperf
      - name: Unit Testing
        run: |
          export LD_LIBRARY_PATH=`pwd`/thirdparty/output/lib:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server          
          ulimit -s unlimited
          ./run.sh test --sanitizer address --skip_thirdparty --disable_gperf

  test-with-sanitizer-leak:
    name: Test With Sanitizer Leak
    needs: lint
    runs-on: self-hosted
    container:
      image: apachepegasus/thirdparties-bin:ubuntu1804
      env:
        CCACHE_DIR: /tmp/ccache/pegasus
        CCACHE_MAXSIZE: 10G
      volumes:
        # Place ccache compilation intermediate results in host memory, that's shared among containers.
        - /tmp/ccache/pegasus:/tmp/ccache/pegasus
      # Read docs at https://docs.docker.com/storage/tmpfs/ for more details of using tmpfs in docker.
      options: --mount type=tmpfs,destination=/tmp/pegasus --cap-add=SYS_PTRACE
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
      - name: Unpack prebuilt third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty') == false
        run: unzip /root/thirdparties-bin.zip -d ./thirdparty
      - name: Rebuild third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty')
        working-directory: thirdparty
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -B build/
          cmake --build build/ -j $(($(nproc)/2+1))
      - name: Compilation
        run: ./run.sh build -c --sanitizer leak --skip_thirdparty --disable_gperf
      - name: Unit Testing
        run: |
          export LD_LIBRARY_PATH=`pwd`/thirdparty/output/lib:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server          
          ulimit -s unlimited
          ./run.sh test --sanitizer leak --skip_thirdparty --disable_gperf

  test-with-sanitizer-undefined:
    name: Test With Sanitizer Undefined
    needs: lint
    runs-on: self-hosted
    container:
      image: apachepegasus/thirdparties-bin:ubuntu1804
      env:
        CCACHE_DIR: /tmp/ccache/pegasus
        CCACHE_MAXSIZE: 10G
      volumes:
        # Place ccache compilation intermediate results in host memory, that's shared among containers.
        - /tmp/ccache/pegasus:/tmp/ccache/pegasus
      # Read docs at https://docs.docker.com/storage/tmpfs/ for more details of using tmpfs in docker.
      options: --mount type=tmpfs,destination=/tmp/pegasus --cap-add=SYS_PTRACE
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
      - name: Unpack prebuilt third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty') == false
        run: unzip /root/thirdparties-bin.zip -d ./thirdparty
      - name: Rebuild third-parties
        if: contains(steps.changed-files.outputs.modified_files, 'thirdparty')
        working-directory: thirdparty
        run: |
          mkdir build
          cmake -DCMAKE_BUILD_TYPE=Release -B build/
          cmake --build build/ -j $(($(nproc)/2+1))
      - name: Compilation
        run: ./run.sh build -c --sanitizer undefined --skip_thirdparty --disable_gperf
      - name: Unit Testing
        run: |
          export LD_LIBRARY_PATH=`pwd`/thirdparty/output/lib:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server          
          ulimit -s unlimited
          ./run.sh test --sanitizer undefined --skip_thirdparty --disable_gperf
